// MOVOKA Cloudflare Worker
// 영화 데이터는 KV에 저장하고 영화관 상영 여부는 체인별 실시간 데이터로 확인합니다.
const KOFIC_BASE='https://www.kobis.or.kr/kobisopenapi/webservice/rest';
const KOBIS_WEB_BASE='https://www.kobis.or.kr';
const CINEMA_API_BASE='https://mcp.aka.page/api';
const GENRE_MAP={'공포(호러)':'공포','호러':'공포','코미디':'코미디','스릴러':'스릴러','액션':'액션','드라마':'드라마','멜로/로맨스':'멜로/로맨스','애니메이션':'애니메이션','SF':'SF','판타지':'판타지','범죄':'범죄','미스터리':'미스터리','모험':'모험','전쟁':'전쟁','다큐멘터리':'다큐멘터리'};
const CGV_REGIONS=['01','02','202','12','03','11','05','204','206'];
const MEGABOX_REGIONS=['11','26','27','28','29','30','31','36','41','42','43','44','45','46','47','48','50'];
function json(data,status=200,extraHeaders={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...extraHeaders}})}
function normalizeGenres(genres=[]){return [...new Set(genres.map(item=>GENRE_MAP[item.genreNm]||item.genreNm).filter(Boolean))]}
function normalizeTitle(value=''){return String(value).toLowerCase().replace(/\([^)]*\)/g,'').replace(/\[[^\]]*\]/g,'').replace(/[^0-9a-z가-힣]/gi,'')}
async function fetchWithTimeout(url,options={},timeoutMs=12000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function fetchJson(url){try{const response=await fetchWithTimeout(url,{redirect:'follow',headers:{accept:'application/json','user-agent':'MOVOKA/1.0'}});if(!response.ok)return null;return await response.json()}catch(error){console.error(`MOVOKA cinema API error (${url}):`,error);return null}}
function getData(response){return response?.data||response?.result||response||{}}
function extractMovieNames(response){const data=getData(response);const names=[];for(const movie of Array.isArray(data.movies)?data.movies:[]){const name=movie?.movieName||movie?.movieNm||movie?.movNm||movie?.name;if(name)names.push(String(name))}for(const show of Array.isArray(data.showtimes)?data.showtimes:[]){const name=show?.movieName||show?.movieNm||show?.movNm||show?.name;if(name)names.push(String(name))}for(const product of Array.isArray(data.standard?.products)?data.standard.products:[]){const name=product?.name||product?.movieName;if(name)names.push(String(name))}return [...new Set(names)]}
async function runPool(items,worker,concurrency=6){const results=[];let cursor=0;async function runner(){while(true){const index=cursor++;if(index>=items.length)return;results[index]=await worker(items[index])}}await Promise.all(Array.from({length:Math.min(concurrency,items.length)},runner));return results}
function getKoreaDateToday(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}${v.month}${v.day}`}
// 홈페이지 HTML 대신 실제 영화관 데이터 API를 사용합니다. 정상 응답에서 영화명이 확인된 체인만 버튼을 만듭니다.
async function getCinemaAvailability(movies){const playDate=getKoreaDateToday();const verified={CGV:{ok:false,titles:new Set()},롯데시네마:{ok:false,titles:new Set()},메가박스:{ok:false,titles:new Set()}};
const lotte=await fetchJson(`${CINEMA_API_BASE}/lottecinema/movies?playDate=${playDate}`);if(lotte){verified['롯데시네마'].ok=true;extractMovieNames(lotte).forEach(n=>verified['롯데시네마'].titles.add(normalizeTitle(n)))}
const mega=await runPool(MEGABOX_REGIONS,region=>fetchJson(`${CINEMA_API_BASE}/megabox/movies?playDate=${playDate}&areaCode=${region}`),6);mega.forEach(r=>{if(!r)return;verified.메가박스.ok=true;extractMovieNames(r).forEach(n=>verified.메가박스.titles.add(normalizeTitle(n)))});
const theaterResponses=await runPool(CGV_REGIONS,region=>fetchJson(`${CINEMA_API_BASE}/cgv/theaters?playDate=${playDate}&regionCode=${region}&limit=100`),6);const codes=[];theaterResponses.forEach(r=>{const theaters=getData(r)?.theaters;if(!Array.isArray(theaters))return;theaters.slice(0,3).forEach(t=>{const code=t?.theaterCode||t?.code;if(code)codes.push(String(code))})});
const cgv=await runPool([...new Set(codes)],code=>fetchJson(`${CINEMA_API_BASE}/cgv/movies?playDate=${playDate}&theaterCode=${encodeURIComponent(code)}`),6);cgv.forEach(r=>{if(!r)return;verified.CGV.ok=true;extractMovieNames(r).forEach(n=>verified.CGV.titles.add(normalizeTitle(n)))});
const anyVerified=Object.values(verified).some(v=>v.ok);return movies.map(movie=>{const title=normalizeTitle(movie.title);if(!anyVerified)return {...movie,cinemas:Array.isArray(movie.cinemas)?movie.cinemas:[]};const cinemas=Object.keys(verified).filter(chain=>verified[chain].ok&&verified[chain].titles.has(title));return {...movie,cinemas}})}
function getKoreaDateMinusOne(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));const utc=new Date(Date.UTC(Number(v.year),Number(v.month)-1,Number(v.day)));utc.setUTCDate(utc.getUTCDate()-1);return utc.toISOString().slice(0,10).replaceAll('-','')}
async function getKoficJson(url){const response=await fetch(url,{redirect:'follow'});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`KOBIS_NON_JSON_HTTP_${response.status}`)}if(!response.ok)throw new Error(`KOBIS_HTTP_${response.status}`);if(data?.faultResult){const f=data.faultResult;throw new Error(`KOBIS_${f.errorCode||'API_ERROR'}:${f.faultInfo||'API 오류'}`)}return data}
async function getPosterMap(targetDt){const url=new URL(`${KOBIS_WEB_BASE}/kobis/business/main/searchMainDailyBoxOffice.do`);url.searchParams.set('startDate',`${targetDt.slice(0,4)}.${targetDt.slice(4,6)}.${targetDt.slice(6,8)}`);url.searchParams.set('endDate',`${targetDt.slice(0,4)}.${targetDt.slice(4,6)}.${targetDt.slice(6,8)}`);const response=await fetch(url,{redirect:'follow'});if(!response.ok)throw new Error(`KOBIS_POSTER_PAGE_HTTP_${response.status}`);const rows=await response.json();const map=new Map();for(const row of Array.isArray(rows)?rows:[]){if(!row?.movieCd)continue;let poster='';if(row.fileSaveLoct&&row.sysFileNm)poster=new URL(`${row.fileSaveLoct}${row.sysFileNm}`,KOBIS_WEB_BASE).href;if(!poster&&row.thumbUrl)poster=new URL(row.thumbUrl,KOBIS_WEB_BASE).href;if(poster)map.set(String(row.movieCd),poster)}return map}
async function getMovieInfoFromKobis(movieCd){const response=await fetchWithTimeout(`${KOBIS_WEB_BASE}/kobis/business/main/searchMainRealTicket.do`,{redirect:'follow',headers:{accept:'application/json'}},5000);if(!response.ok)throw new Error(`KOBIS_MOVIE_INFO_HTTP_${response.status}`);const rows=await response.json();const movie=(Array.isArray(rows)?rows:[]).find(row=>String(row?.movieCd)===String(movieCd));if(!movie)return{plot:'',director:'',trailer:''};return{plot:String(movie.synop||'').trim(),director:String(movie.director||'').trim(),trailer:''}}
async function collectMovies(env){const key=env.KOBIS_API_KEY;if(!key)return{ok:false,code:'KOBIS_API_KEY_MISSING',message:'KOBIS_API_KEY 환경변수가 설정되지 않았습니다.'};const targetDt=getKoreaDateMinusOne();const boxofficeUrl=new URL(`${KOFIC_BASE}/boxoffice/searchDailyBoxOfficeList.json`);boxofficeUrl.searchParams.set('key',key);boxofficeUrl.searchParams.set('targetDt',targetDt);const boxofficeData=await getKoficJson(boxofficeUrl);const candidates=(boxofficeData?.boxOfficeResult?.dailyBoxOfficeList||[]).slice(0,20);const posterPromise=getPosterMap(targetDt).catch(error=>{console.error('MOVOKA poster error:',error);return new Map()});const detailPromises=candidates.map(async item=>{const detailUrl=new URL(`${KOFIC_BASE}/movie/searchMovieInfo.json`);detailUrl.searchParams.set('key',key);detailUrl.searchParams.set('movieCd',item.movieCd);try{const data=await getKoficJson(detailUrl);const movie=data?.movieInfoResult?.movieInfo;if(!movie)return null;return{id:movie.movieCd,title:movie.movieNm,date:movie.openDt?`${movie.openDt.slice(0,4)}-${movie.openDt.slice(4,6)}-${movie.openDt.slice(6,8)}`:'',genres:normalizeGenres(movie.genres),rating:movie.audits?.[0]?.watchGradeNm||'',runtime:movie.showTm||'',rank:Number(item.rank)||999,audience:Number(item.audiAcc)||0,screens:Number(item.scrnCnt)||0,poster:'',cinemas:[]}}catch(error){console.error(`MOVOKA movie detail error (${item.movieCd}):`,error);return null}});const[posterMap,detailMovies]=await Promise.all([posterPromise,Promise.all(detailPromises)]);const movies=detailMovies.filter(Boolean).map(movie=>({...movie,poster:posterMap.get(String(movie.id))||''})).sort((a,b)=>a.rank-b.rank);const verifiedMovies=await getCinemaAvailability(movies);return{ok:true,source:'KOFIC/KOBIS',basedAt:targetDt,cinemaCheckedAt:new Date().toISOString(),movies:verifiedMovies}}
async function refreshCinemaLinks(env){const stored=await env.MOVIE_DATA.get('latest',{type:'json'});if(!stored?.ok||!Array.isArray(stored.movies))return null;const movies=await getCinemaAvailability(stored.movies);const data={...stored,cinemaCheckedAt:new Date().toISOString(),movies};await env.MOVIE_DATA.put('latest',JSON.stringify(data));return data}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/movies'){let stored=await env.MOVIE_DATA.get('latest',{type:'json'});if(stored?.ok&&Array.isArray(stored.movies)){const hasCinemaData=stored.movies.some(movie=>Array.isArray(movie.cinemas)&&movie.cinemas.length>0);const checkedAt=stored.cinemaCheckedAt?Date.parse(stored.cinemaCheckedAt):0;const cinemaStale=!checkedAt||(Date.now()-checkedAt>3*60*60*1000)||!hasCinemaData;if(cinemaStale){const refreshed=await refreshCinemaLinks(env);if(refreshed)stored=refreshed}return json(stored,200,{'cache-control':'no-store'})}return json({ok:false,code:'MOVIE_DATA_NOT_READY',message:'오늘의 영화 데이터가 아직 준비되지 않았습니다.'},503)}if(url.pathname==='/api/movie-info'){const movieCd=url.searchParams.get('movieCd');if(!movieCd)return json({ok:false,message:'movieCd가 필요합니다.'},400);try{const info=await getMovieInfoFromKobis(movieCd);return json({ok:true,...info},200,{'cache-control':'public, max-age=21600'})}catch(error){console.error('MOVOKA movie info error:',error);return json({ok:false,message:'영화 정보를 불러오지 못했습니다.'},502)}}if(url.pathname==='/internal/refresh-movies'&&request.method==='POST'){const data=await collectMovies(env);if(!data.ok)return json(data,503);await env.MOVIE_DATA.put('latest',JSON.stringify(data));return json({ok:true,basedAt:data.basedAt,count:data.movies.length})}if(url.pathname==='/internal/refresh-cinema-links'&&request.method==='POST'){const data=await refreshCinemaLinks(env);if(!data)return json({ok:false,message:'영화 데이터가 없습니다.'},503);return json({ok:true,cinemaCheckedAt:data.cinemaCheckedAt})}const assetResponse=await env.ASSETS.fetch(request);const contentType=assetResponse.headers.get('content-type')||'';if(contentType.includes('text/html'))return new HTMLRewriter().on('body',{element(element){element.append('<script src="/movoka-live.js?v=20260913-16" defer></script>',{html:true})}}).transform(assetResponse);return assetResponse},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{const data=await collectMovies(env);if(data.ok)await env.MOVIE_DATA.put('latest',JSON.stringify(data))})())}};